version: '3.8'

services:
  postgres:
    image: postgres:16.11-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ya_blog
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - ftmpt-blog

networks:
  ftmpt-blog:
    driver: bridge
